FROM eclipse-mosquitto
COPY entrypoint.sh /entrypoint.sh
ENTRYPOINT ["sh", "/entrypoint.sh"]
CMD ["/usr/sbin/mosquitto","-c","/mosquitto/config/mosquitto.conf"]

#RUN chmod 0700 /mosquitto/config/pwfile
#RUN chown root /mosquitto/config/pwfile
#RUN mosquitto_passwd -U /mosquitto/config/pwfile
