services:
  psm-updater:
    image: farsonic/docker-psm-event-updater:latest
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    environment:
      PSM_IPADDRESS: "$IpPSM"
      PSM_USERNAME: "$UserPSM"
      PSM_PASSWORD: "$PasswordPSM"