#version: '3'
services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: dockerfile-backend

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    volumes:
      - ./config:/mosquitto/config
      - ./data/mqtt:/mosquitto/data
      - ./log:/mosquitto/log
    build: 
      context: .
      dockerfile: dockerfile-mosquitto
#    depends_on:
#      - db
    ports:
      - "1883:1883"
      - "9001:9001" #default mqtt port for websockets
    restart: always

  db:
    container_name: mysql-server
    image: mysql:5.7
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    volumes:
      - ./data/sql:/var/lib/mysql:rw
      - ./config/MQTT.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Pensando0$$
      MYSQL_DATABASE: MQTT
      MYSQL_USER: mqtt
      MYSQL_PASSWORD: mqtt
    ports:
      - "3306:3306"

  frontend1:
    container_name: php-apache
    build: 
      context: .
      dockerfile: dockerfile-frontend
    #image: php:8.2-apache

    volumes:
      - ./data/frontend1:/var/www/html/
    ports:
      - 8080:80

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    links:
    - db
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
     - 8081:80

volumes:
  db_data: {}
  config:
  data:
  log: